mode: 'fix'
model:
  engine_file: "/home/nvidia/Desktop/FCOSR/model/fcosr_tiny_agx_16.trt"
  labels: 'labels.txt'
io:
  input_dir: '/data/cache/'
  output_dir: 'result'
preprocess:
  num_process: 8
  queue_length: 48
  normalization:
    enable: 1
    mean:
      - 123.675
      - 116.28
      - 103.53
    std:
      - 58.395
      - 57.12
      - 57.375
postprocess:
  num_process: 8
  queue_length: 48
  nms_threshold: 0.1
  score_threshold: 0.3
  max_det_num: 2000
  draw_image:
    enable: 1
    num: 'all'